name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest changes from repository
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'cd Documents/GitHub/wesplit && git pull'

      - name: Install server dependencies
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} -p 2222 ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'cd Documents/GitHub/wesplit && npm install'

      - name: Install client dependencies
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} -p 2222 ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'cd Documents/GitHub/wesplit/client && npm install'

      - name: Start server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} -p 2222 ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'cd Documents/GitHub/wesplit && npm run dev'

      - name: Start client
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} -p 2222 ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'cd Documents/GitHub/wesplit/client && npm start'
